name = "NumericallyIntegrateArray"
uuid = "5cb755e0-53b8-11e9-35b5-090ec4427b57"
authors = ["Jishnu Bhattacharya <jishnuonline@gmail.com>"]
version = "0.1.0"

[deps]
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
